import requests
import pandas as pd

http_api_url = "https://api.rescuegroups.org/http/v2.json"
session = requests.session()
username = "YOUR USERNAME"
password = "YOUR PASSWORD"
accountNumber = YOUR ACCOUNT NUMBER
exportDirectory = "/EXPORT/DIRECTORY"

def login(username, password, accountNumber):
    data = {
        "username": username,
        "password": password,
        "accountNumber": accountNumber,
        "action": "login",
    }
    headers = {"Content-Type": "application/json"}
    response = session.post(http_api_url, json=data, headers=headers).json()
    return response["data"]["token"], response["data"]["tokenHash"]


def getAnimals(token, tokenHash):
    data = {
        "token": token,
        "tokenHash": tokenHash,
        "objectType": "animals",
        "objectAction": "search",
        "search": {
            "calcFoundRows": "Yes",
            "resultStart": 0,
            "resultLimit": 2000,
            "resultSort": "animalID",
            "fields": [
                "animalID",
                "animalActivityLevel",
                "animalAdoptedDate",
                "animalAdoptionFee",
                "animalAdoptionLead",
                "animalAdoptionLeadID",
                "animalAltered",
                "animalApplicationID",
                "animalAvailableDate",
                "animalBirthdate",
                "animalBirthdateExact",
                "animalBreed",
                "animalCoatLength",
                "animalColonyID",
                "animalColor",
                "animalColorID",
                "animalColorDetails",
                "animalCondition",
                "animalConditionID",
                "animalCost",
                "animalCourtesy",
                "animalCreatedDate",
                "animalCreatedBy",
                "animalCreatedByID",
                "animalCreatedTimeframe",
                "animalDaysInFoster",
                "animalDeclawed",
                "animalDescription",
                "animalDescriptionPlain",
                "animalDistinguishingMarks",
                "animalAllowExport",
                "animalEarType",
                "animalEnergyLevel",
                "animalExerciseNeeds",
                "animalEyeColor",
                "animalFence",
                "animalFosterID",
                "animalFound",
                "animalFoundDate",
                "animalFoundPostalcode",
                "animalGeneralAge",
                "animalGeneralSizePotential",
                "animalGroomingNeeds",
                "animalHighlightOrder",
                "animalHousetrained",
                "animalIndoorOutdoor",
                "animalIntakes",
                "animalInternalID",
                "animalKillDate",
                "animalKillReason",
                "animalUpdatedBy",
                "animalUpdatedByID",
                "animalUpdatedDate",
                "animalUpdatedTimeframe",
                "animalLocationID",
                "animalLocationPublic",
                "animalMicrochipped",
                "animalMicrochipNumber",
                "animalMicrochipVendor",
                "animalMixedBreed",
                "animalName",
                "animalSpecialneeds",
                "animalSpecialneedsDescription",
                "animalNeedsFoster",
                "animalNewPeople",
                "animalNotes",
                "animalNotHousetrainedReason",
                "animalObedienceTraining",
                "animalOKWithAdults",
                "animalOKWithCats",
                "animalOKWithDogs",
                "animalOKWithKids",
                "animalOpenIntakes",
                "animalOrigin",
                "animalOthernames",
                "animalOutcomes",
                "animalOwnerExperience",
                "animalOwnerID",
                "animalPattern",
                "animalPatternID",
                "animalAdoptionPending",
                "animalPrimaryBreed",
                "animalPrimaryBreedID",
                "animalReceivedDate",
                "animalRescueID",
                "animalSecondaryBreed",
                "animalSecondaryBreedID",
                "animalSex",
                "animalShared",
                "animalShedding",
                "animalSizeCurrent",
                "animalSizePotential",
                "animalSizeUOM",
                "animalSpecies",
                "animalSpeciesID",
                "animalSponsorable",
                "animalSponsors",
                "animalSponsorshipDetails",
                "animalSponsorshipMinimum",
                "animalStatus",
                "animalStatusID",
                "animalSummary",
                "animalTailType",
                "animalTransferredToID",
                "animalUptodate",
                "animalVocal",
                "animalYardRequired",
                "animalAffectionate",
                "animalApartment",
                "animalCratetrained",
                "animalDrools",
                "animalEagerToPlease",
                "animalEscapes",
                "animalEventempered",
                "animalFetches",
                "animalGentle",
                "animalGoodInCar",
                "animalGoofy",
                "animalHasAllergies",
                "animalHearingImpaired",
                "animalHypoallergenic",
                "animalIndependent",
                "animalIntelligent",
                "animalLap",
                "animalLeashtrained",
                "animalNeedsCompanionAnimal",
                "animalNoCold",
                "animalNoFemaleDogs",
                "animalNoHeat",
                "animalNoLargeDogs",
                "animalNoMaleDogs",
                "animalNoSmallDogs",
                "animalObedient",
                "animalOKForSeniors",
                "animalOKWithFarmAnimals",
                "animalOlderKidsOnly",
                "animalOngoingMedical",
                "animalPlayful",
                "animalPlaysToys",
                "animalPredatory",
                "animalProtective",
                "animalSightImpaired",
                "animalSkittish",
                "animalSpecialDiet",
                "animalSwims",
                "animalTimid",
                "ownerID",
                "ownerActive",
                "ownerAddress",
                "ownerBounces",
                "ownerCarrier",
                "ownerCity",
                "ownerComment",
                "ownerCompany",
                "ownerCountry",
                "ownerCounty",
                "ownerEmail",
                "ownerEmailAlt",
                "ownerEmailPager",
                "ownerFax",
                "ownerFirstname",
                "ownerLastname",
                "ownerName",
                "ownerPhoneCell",
                "ownerPhoneHome",
                "ownerPhoneWork",
                "ownerPhoneWorkExt",
                "ownerPlus4",
                "ownerReferredBy",
                "ownerSalutation",
                "ownerSendMail",
                "ownerState",
                "ownerTitle",
                "ownerPostalcode",
                "colonyAnimals",
                "colonyCaretakers",
                "colonyLocation",
                "colonyLocationID",
                "colonyName",
                "colonyRegisteredDate",
                "colonySpecificLocation",
                "fosterID",
                "fosterActive",
                "fosterAddress",
                "fosterBounces",
                "fosterCarrier",
                "fosterCity",
                "fosterComment",
                "fosterCompany",
                "fosterCountry",
                "fosterCounty",
                "fosterEmail",
                "fosterEmailAlt",
                "fosterEmailPager",
                "fosterFax",
                "fosterFirstname",
                "fosterLastname",
                "fosterName",
                "fosterPhoneCell",
                "fosterPhoneHome",
                "fosterPhoneWork",
                "fosterPhoneWorkExt",
                "fosterPlus4",
                "fosterReferredBy",
                "fosterSalutation",
                "fosterSendMail",
                "fosterState",
                "fosterTitle",
                "fosterPostalcode",
                "locationAddress",
                "locationAnimals",
                "locationCity",
                "locationColonies",
                "locationCountry",
                "locationUrl",
                "locationEvents",
                "locationMeetrequests",
                "locationName",
                "locationPhone",
                "locationState",
                "locationPostalcode",
                "submittedformID",
                "submittedformAnimalID",
                "submittedformAssignedToID",
                "submittedformCommentsCount",
                "submittedformCommentsInline",
                "submittedformCompletedDate",
                "submittedformFormName",
                "submittedformPending",
                "submittedformStatus",
                "submittedformStepsCount",
                "submitterID",
                "submitterActive",
                "submitterAddress",
                "submitterBounces",
                "submitterCarrier",
                "submitterCity",
                "submitterComment",
                "submitterCompany",
                "submitterCountry",
                "submitterCounty",
                "submitterEmail",
                "submitterEmailAlt",
                "submitterEmailPager",
                "submitterFax",
                "submitterFirstname",
                "submitterLastname",
                "submitterName",
                "submitterPhoneCell",
                "submitterPhoneHome",
                "submitterPhoneWork",
                "submitterPhoneWorkExt",
                "submitterPlus4",
                "submitterReferredBy",
                "submitterSalutation",
                "submitterSendMail",
                "submitterState",
                "submitterTitle",
                "submitterPostalcode",
                "transferredtoActive",
                "transferredtoAddress",
                "transferredtoBounces",
                "transferredtoCarrier",
                "transferredtoCity",
                "transferredtoComment",
                "transferredtoCompany",
                "transferredtoID",
                "transferredtoCountry",
                "transferredtoCounty",
                "transferredtoEmail",
                "transferredtoEmailAlt",
                "transferredtoEmailPager",
                "transferredtoFax",
                "transferredtoFirstname",
                "transferredtoLastname",
                "transferredtoName",
                "transferredtoPhoneCell",
                "transferredtoPhoneHome",
                "transferredtoPhoneWork",
                "transferredtoPhoneWorkExt",
                "transferredtoPlus4",
                "transferredtoReferredBy",
                "transferredtoSalutation",
                "transferredtoSendMail",
                "transferredtoState",
                "transferredtoTitle",
                "transferredtoPostalcode",
                "animalGroups",
                "animalExportAccounts",
                "animalPictures",
            ],
        },
    }

    headers = {"Content-Type": "application/json"}
    response = session.post(http_api_url, json=data, headers=headers).json()
    return response


token, tokenHash = login(username, password, accountNumber)
animal_data = getAnimals(token, tokenHash)
animalData = []
for a in animal_data["data"]:
    animalData.append(animal_data["data"][a])


pd.DataFrame(animalData).to_csv(f"{exportDirectory}rescuegroups_export.csv")
